/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ListEntityTypesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-02-24T16:28:19.559+02:00")
public class ListEntityTypesResponse {
  @SerializedName("type")
  private String type = null;

  @SerializedName("attrs")
  private Object attrs = null;

  @SerializedName("count")
  private Integer count = null;

  public ListEntityTypesResponse type(String type) {
    this.type = type;
    return this;
  }

   /**
   * 
   * @return type
  **/
  @ApiModelProperty(example = "Car", required = true, value = "")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public ListEntityTypesResponse attrs(Object attrs) {
    this.attrs = attrs;
    return this;
  }

   /**
   * 
   * @return attrs
  **/
  @ApiModelProperty(example = "{\"speed\":{\"types\":[\"Number\"]},\"fuel\":{\"types\":[\"gasoline\",\"diesel\"]},\"temperature\":{\"types\":[\"urn:phenomenum:temperature\"]}}", required = true, value = "")
  public Object getAttrs() {
    return attrs;
  }

  public void setAttrs(Object attrs) {
    this.attrs = attrs;
  }

  public ListEntityTypesResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * 
   * @return count
  **/
  @ApiModelProperty(example = "12", required = true, value = "")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListEntityTypesResponse listEntityTypesResponse = (ListEntityTypesResponse) o;
    return Objects.equals(this.type, listEntityTypesResponse.type) &&
        Objects.equals(this.attrs, listEntityTypesResponse.attrs) &&
        Objects.equals(this.count, listEntityTypesResponse.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, attrs, count);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListEntityTypesResponse {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

