/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * QueryRequest
 */
@JsonPropertyOrder({
  QueryRequest.JSON_PROPERTY_ENTITIES,
  QueryRequest.JSON_PROPERTY_ATTRS,
  QueryRequest.JSON_PROPERTY_EXPRESSION,
  QueryRequest.JSON_PROPERTY_METADATA
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-02-24T16:35:36.823283+02:00[Europe/Athens]")
public class QueryRequest {
  public static final String JSON_PROPERTY_ENTITIES = "entities";
  private List<Object> entities = new ArrayList<>();

  public static final String JSON_PROPERTY_ATTRS = "attrs";
  private List<String> attrs = new ArrayList<>();

  public static final String JSON_PROPERTY_EXPRESSION = "expression";
  private Object expression;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  private List<String> metadata = new ArrayList<>();


  public QueryRequest entities(List<Object> entities) {
    
    this.entities = entities;
    return this;
  }

  public QueryRequest addEntitiesItem(Object entitiesItem) {
    this.entities.add(entitiesItem);
    return this;
  }

   /**
   * 
   * @return entities
  **/
  @ApiModelProperty(example = "[{idPattern=.*, type=Room}, {id=Car, type=P-9873-K}]", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ENTITIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<Object> getEntities() {
    return entities;
  }


  public void setEntities(List<Object> entities) {
    this.entities = entities;
  }


  public QueryRequest attrs(List<String> attrs) {
    
    this.attrs = attrs;
    return this;
  }

  public QueryRequest addAttrsItem(String attrsItem) {
    this.attrs.add(attrsItem);
    return this;
  }

   /**
   * 
   * @return attrs
  **/
  @ApiModelProperty(example = "[temperature, humidity]", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ATTRS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getAttrs() {
    return attrs;
  }


  public void setAttrs(List<String> attrs) {
    this.attrs = attrs;
  }


  public QueryRequest expression(Object expression) {
    
    this.expression = expression;
    return this;
  }

   /**
   * 
   * @return expression
  **/
  @ApiModelProperty(example = "{\"q\":\"temperature>20\"}", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_EXPRESSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Object getExpression() {
    return expression;
  }


  public void setExpression(Object expression) {
    this.expression = expression;
  }


  public QueryRequest metadata(List<String> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public QueryRequest addMetadataItem(String metadataItem) {
    this.metadata.add(metadataItem);
    return this;
  }

   /**
   * 
   * @return metadata
  **/
  @ApiModelProperty(example = "[accuracy, timestamp]", required = true, value = "")
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<String> getMetadata() {
    return metadata;
  }


  public void setMetadata(List<String> metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryRequest queryRequest = (QueryRequest) o;
    return Objects.equals(this.entities, queryRequest.entities) &&
        Objects.equals(this.attrs, queryRequest.attrs) &&
        Objects.equals(this.expression, queryRequest.expression) &&
        Objects.equals(this.metadata, queryRequest.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entities, attrs, expression, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryRequest {\n");
    sb.append("    entities: ").append(toIndentedString(entities)).append("\n");
    sb.append("    attrs: ").append(toIndentedString(attrs)).append("\n");
    sb.append("    expression: ").append(toIndentedString(expression)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

