/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Options3
 */
public class Options3Test {
    /**
     * Model tests for Options3
     */
    @Test
    public void testOptions3() {
        // TODO: test Options3
    }

}
