/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RetrieveApiResourcesResponse
 */
public class RetrieveApiResourcesResponseTest {
    private final RetrieveApiResourcesResponse model = new RetrieveApiResourcesResponse();

    /**
     * Model tests for RetrieveApiResourcesResponse
     */
    @Test
    public void testRetrieveApiResourcesResponse() {
        // TODO: test RetrieveApiResourcesResponse
    }

    /**
     * Test the property 'entitiesUrl'
     */
    @Test
    public void entitiesUrlTest() {
        // TODO: test entitiesUrl
    }

    /**
     * Test the property 'typesUrl'
     */
    @Test
    public void typesUrlTest() {
        // TODO: test typesUrl
    }

    /**
     * Test the property 'subscriptionsUrl'
     */
    @Test
    public void subscriptionsUrlTest() {
        // TODO: test subscriptionsUrl
    }

    /**
     * Test the property 'registrationsUrl'
     */
    @Test
    public void registrationsUrlTest() {
        // TODO: test registrationsUrl
    }

}
