/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RetrieveEntityAttributesResponse
 */
public class RetrieveEntityAttributesResponseTest {
    private final RetrieveEntityAttributesResponse model = new RetrieveEntityAttributesResponse();

    /**
     * Model tests for RetrieveEntityAttributesResponse
     */
    @Test
    public void testRetrieveEntityAttributesResponse() {
        // TODO: test RetrieveEntityAttributesResponse
    }

    /**
     * Test the property 'temperature'
     */
    @Test
    public void temperatureTest() {
        // TODO: test temperature
    }

    /**
     * Test the property 'humidity'
     */
    @Test
    public void humidityTest() {
        // TODO: test humidity
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

}
