/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RetrieveApiResourcesResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ApiEntryPointApi
 */
@Ignore
public class ApiEntryPointApiTest {

    private final ApiEntryPointApi api = new ApiEntryPointApi();

    
    /**
     * Retrieve API Resources
     *
     * This resource does not have any attributes. Instead it offers the initial API affordances in the form of the links in the JSON body. It is recommended to follow the “url” link values, [Link](https://tools.ietf.org/html/rfc5988) or Location headers where applicable to retrieve resources. Instead of constructing your own URLs, to keep your client decoupled from implementation details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveAPIResourcesTest() throws ApiException {
        RetrieveApiResourcesResponse response = api.retrieveAPIResources();

        // TODO: test validations
    }
    
}
