/*
 * FIWARE-NGSI v2 Specification
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.CreateSubscriptionRequest;
import io.swagger.client.model.ListSubscriptionsResponse;
import io.swagger.client.model.UpdateSubscriptionRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubscriptionsApi
 */
@Ignore
public class SubscriptionsApiTest {

    private final SubscriptionsApi api = new SubscriptionsApi();

    
    /**
     * Create Subscription
     *
     * Creates a new subscription. The subscription is represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 201 Created * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createSubscriptionTest() throws ApiException {
        String contentType = null;
        CreateSubscriptionRequest body = null;
        api.createSubscription(contentType, body);

        // TODO: test validations
    }
    
    /**
     * Delete subscription
     *
     * Cancels subscription. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        api.deleteSubscription(subscriptionId);

        // TODO: test validations
    }
    
    /**
     * List Subscriptions
     *
     * Returns a list of all the subscriptions present in the system. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listSubscriptionsTest() throws ApiException {
        Double limit = null;
        Double offset = null;
        String options = null;
        List<ListSubscriptionsResponse> response = api.listSubscriptions(limit, offset, options);

        // TODO: test validations
    }
    
    /**
     * Retrieve Subscription
     *
     * The response is the subscription represented by a JSON object as described at the beginning of this section. Response: * Successful operation uses 200 OK * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        Object response = api.retrieveSubscription(subscriptionId);

        // TODO: test validations
    }
    
    /**
     * Update Subscription
     *
     * Only the fields included in the request are updated in the subscription. Response: * Successful operation uses 204 No Content * Errors use a non-2xx and (optionally) an error payload. See subsection on \&quot;Error Responses\&quot; for   more details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateSubscriptionTest() throws ApiException {
        String subscriptionId = null;
        String contentType = null;
        UpdateSubscriptionRequest body = null;
        api.updateSubscription(subscriptionId, contentType, body);

        // TODO: test validations
    }
    
}
